### ISSUE TITLE
'Alpha' is not a valid FeatureStateEnum

### ISSUE THREAD

**Issue by alexdaley** [codatio/client-sdk-python#99]
Having an issue when calling `common.integrations.list_integrations`:

```
'Alpha' is not a valid FeatureStateEnum
```

I see in `common.models.shared.FeatureStateEnum`, "Alpha" is not one of the options. Looking into the response, I see that the Alpha feature is in the Quickbooks Desktop integration.

**Comment by mcclowes** [comment]
Thanks Alex, I'll get that fixed asap

**Comment by dcoplowe** [comment]
Hi Alex, 

We've release a new version of our python library which includes a fix for the `FeatureStateEnum`.

Thank you for raising this and please let us know if you run into any other issues. 

Many thanks,

David
